

mqtt:
  username: admin
  password: admin
  hostUrl: tcp://127.0.0.1:8080		# 你自己服务器的地址和端口，这个需要改
  clientID: test							# 这个改不改随意，但不同的客户端肯定不能一样
  defaultTopic: test						# 默认主题
  timeout: 100
  keepalive: 100
  qos: 0  #消息发送模式 0：最多一次  1：最少一次  2：只有一次
server:
  port: 8081
spring:
  application:
    name: mqtt-service

